### PR TITLE
amethst.md

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by mlhenderson** [comment]
Hmm, this particular repo has a submodule that points back to MG-RAST.  I'm guessing that is where the meat of this is.

@levinas or @wgerlach, can you comment on what data is being used by amethst in KBase?

**Comment by wgerlach** [comment]
I am mostly responsible for the code in https://github.com/kbase/amethst_service , which is a KBase service to execute code from https://github.com/MG-RAST/AMETHST (author: Kevin Keegan) . I do not know what you are doing. If the fact that this service uses submodules that point to outside of KBase is a problem, I can try to fix that.

**Comment by realmarcin** [comment]
Hi Wolfgang,

As Matt mentioned, we are trying to document the input and output data
types for services. Could you help provide some details on what particular
input and output types you services uses? And from where does the input
data originate?

thanks,
marcin

**Comment by mlhenderson** [comment]
@wgerlach We're simply trying to document data and data types being used by
KBase, focusing first on what is running in production.  This service is
listed as running in production.  Can you help us identify the data sources
and data types being used?

**Comment by wgerlach** [comment]
Input files are all expected to be in Shock, typically uploaded by the user, e.g. using the amethst client script. I'll ask Kevin about the exact file types that are expected and let you know.

**Comment by DrOppenheimer** [comment]
I'll provide input/output info. in the main AMETHST repo. https://github.com/MG-RAST/AMETHST Cheers - Kevin

**Pull request merged**
