### PR TITLE
Create cbd.md

### PR DESCRIPTION
**Pull request by realmarcin**

### CODE REVIEW

**Comment by mlhenderson** [comment]
@mmundy42 we're trying to document the data sources and data types used in production for KBase.  Can you review this doc and provide some additional info for cbd?

**Comment by mmundy42** [comment]
How do you want the comments/updates?  Not sure if you wanted me to wait until this pull request was processed and then update the cbd.md file.

**Comment by mlhenderson** [comment]
@mmundy42 we can do it either way, but I wanted you to have a look at it before I merged it.  Is there anything that is incorrect that should be updated before I merge?

**Comment by mmundy42** [comment]
Here are my updates:

For the Description field: The Compression-Based Distance service uses the relative compression of combined and individual datasets to quantify overlaps between microbial communities and builds a distance matrix of the results.

For Data Sources: Shock

For Input Types:  A set of sequence files for the microbial community.  Sequences are allowed in multiple formats (including FASTQ).

For Output Types: A CSV file with the distance matrix.

**Comment by mlhenderson** [comment]
@realmarcin can you update your PR with mmundy42 comments?

**Comment by mlhenderson** [comment]
@mmundy42 ok, so currently then you are calling this service directly with a client, and it is not connected to other parts of the system?

**Comment by mlhenderson** [comment]
@realmarcin please resubmit with docs in the appropriate directory.

**Comment by mmundy42** [comment]
Yes, the service is called directly with a client and is not currently connected to other parts of the system.  Might have a student help us get it running in the narrative but that is not finalized.  Sorry it took me so long to respond.

**Comment by mmundy42** [comment]
Also, the file in the repo is named with the wrong extension (.cmd instead of .md)

**Comment by realmarcin** [comment]
Matt, I fixed the file name but haven't deleted the old file yet.

**Pull request merged**
